# Generated by Django 5.2.13 on 2026-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_city_order_email_order_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit / Debit Card'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('crypto', 'Cryptocurrency')], default='card', max_length=20),
        ),
    ]
